namespace LiveSplit.Subnautica2
{
    public enum Items
    {
        None = 0,
        AcidAnemoneMedigelSac,
        AcidSacResource,
        AdvancedWiringKit,
        AirBladder,
        BasicBattery,
        Builder,
        ComputerChip,
        ComputerChipMk2,
        Copper,
        CopperWire,
        Fins,
        ImprovedFins,
        IsotonicDrink,
        Flashlight,
        Flares,
        Food,
        Geordie,
        Gold,
        Glass,
        Halfmoon,
        Harvestmoon,
        Lead,
        Lithium,
        LuciferRotsac,
        MedKit,
        MetalSalvage,
        NecroleiEggItem,
        OxygenTankSmall,
        OxygenTankMedium,
        OxygenTankLarge,
        PlantMatter,
        Quartz,
        Rebreather,
        RepairTool,
        Salt,
        Scanner,
        Silver,
        SonicResonator,
        Sulfur,
        SurvivalMultiTool,
        Titanium,
        TitaniumIngot,
        Wakemaker,
        Water,
        WaterSlug,
        PentResource01a,
        WiringKit,
    }
}


